github_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost  # Change to 'postgres' when running inside Docker
      port: 5432
      user: airflow
      password: airflow
      dbname: analytics
      schema: public
      threads: 4
      keepalives_idle: 0
    
    prod:
      type: postgres
      host: postgres
      port: 5432
      user: airflow
      password: airflow
      dbname: analytics
      schema: public
      threads: 4
